services:
  cybersec-scanner:
    build: .
    container_name: cybersec-scanner
    ports:
      - "9001:9001"
    environment:
      - TARGET_DOMAIN=example.com  # Replace your target domain
    restart: unless-stopped

